#!/bin/sh /etc/rc.common

START=80

start() {
	echo "starting adbyby..."
	sleep 30
	/tmp/adbyby/start-adbyby
}

stop() {
	echo "stopping adbyby..."
	/tmp/adbyby/stop-adbyby
}

restart() {
	stop
	sleep 1
	start
}

